# Generated by Django 5.0.6 on 2024-06-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produits",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Commandes",
            fields=[
                ("createdAt", models.DateField()),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("customerId", models.CharField(max_length=255)),
                ("products", models.ManyToManyField(to="Commande.produits")),
            ],
        ),
    ]
