# Generated by Django 5.0.3 on 2024-06-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idCommande', models.BigAutoField(primary_key=True, serialize=False)),
                ('idClient', models.IntegerField(default=0)),
                ('idProduit', models.IntegerField(default=0)),
                ('dateCommande', models.TimeField(verbose_name="date d'achat")),
                ('quantite', models.IntegerField(default=1)),
                ('prix', models.IntegerField(default=0)),
            ],
        ),
    ]
