# Generated by Django 5.1 on 2024-09-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandes',
            name='products',
        ),
    ]
