# Generated by Django 5.0.6 on 2024-06-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Commande", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandes",
            name="customerId",
            field=models.IntegerField(),
        ),
    ]
