# Generated by Django 5.1 on 2024-09-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0002_remove_commandes_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='products',
            field=models.ManyToManyField(to='Commande.produits'),
        ),
    ]
