# Generated by Django 5.0.6 on 2024-06-27 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Commande", "0002_alter_commandes_customerid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandes",
            name="createdAt",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
