# Generated by Django 5.0.6 on 2024-06-27 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Commande", "0003_alter_commandes_createdat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commandes",
            old_name="createdAt",
            new_name="_createdAt",
        ),
        migrations.RenameField(
            model_name="commandes",
            old_name="customerId",
            new_name="_customerId",
        ),
        migrations.RenameField(
            model_name="commandes",
            old_name="id",
            new_name="_id",
        ),
        migrations.RenameField(
            model_name="commandes",
            old_name="products",
            new_name="_products",
        ),
        migrations.RenameField(
            model_name="produits",
            old_name="id",
            new_name="_id",
        ),
    ]
