# Generated by Django 5.0.6 on 2024-06-27 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0004_rename_createdat_commandes__createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandes',
            name='_products',
        ),
        migrations.AddField(
            model_name='commandes',
            name='_products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Commande.produits'),
        ),
    ]
